services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: ./twendeai_server
      dockerfile: Dockerfile
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
         - ./:/app  
    working_dir: /app  
    environment:
        PYTHONPATH: /app
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        SECRET_KEY: ${SECRET_KEY}
        DEBUG: ${DEBUG}
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql_data: