FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y \
    default-libmysqlclient-dev \
    gcc \
    pkg-config \
 && rm -rf /var/lib/apt/lists/*
RUN cat requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .